### ISSUE TITLE
USB host support for stm32f105/107 (FS only)

### ISSUE THREAD

**Issue by lleoha** [ChibiOS/ChibiOS-Contrib#114]
It's not a bug, it's a feature request to add usb host support for stm32f1xx (stm32f105/107 supports USB OTG FS)

**Comment by dismirlian** [comment]
Hi, the USBHv1 driver should support the STM32F105/107; as far I can tell, they have the same OTG core. I can't test the support for these MCUs because I don't have any hardware available, but I have already tested the driver with the F207 and F411. The F105/F107 support the OTG1 (OTG_FS), and have 1280 byte buffers and 8 host channels, just as the F207 and F411 OTG_FS implementation. Watch the pin muxing!

Diego.
